<a href="https://colab.research.google.com/github/CaptJack05/ML/blob/main/__0_pyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pytorch Basics

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


### Types of Tenosr

> Add blockquote



In [ ]:
#Scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim


0

In [ ]:
scalar.shape


torch.Size([])

In [ ]:
#vector
vector = torch.tensor([5,7])
vector


tensor([5, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]],])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
#4-D TENSOR

TENSOR4 = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]],
                       [[1, 2, 3],
                        [4, 5, 6],
                  [7, 8, 9]]])
TENSOR4

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR4.ndim

3

In [ ]:
TENSOR4.shape

torch.Size([2, 3, 3])

### Random Tesors


Why random tesors ?

Random tesnosors are important because the way many neural ntworks learns is that tehy start with tensors full of random numbers and then adjust those random numvers to better represent the data.

'Start with random numbers -> look at data -> update random numbers -> look at data -> update random nmbers '

In [ ]:
# Create a random tensor

random_tensor = torch.rand(1,3,10)
random_tensor

tensor([[[0.6204, 0.6536, 0.6201, 0.0507, 0.5230, 0.7877, 0.5810, 0.7306,
          0.4836, 0.8883],
         [0.4390, 0.2084, 0.6601, 0.4883, 0.7314, 0.8696, 0.0710, 0.4757,
          0.0017, 0.4817],
         [0.4017, 0.3164, 0.6102, 0.8185, 0.7080, 0.4120, 0.3571, 0.7483,
          0.1170, 0.2466]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
random_tensor.shape

torch.Size([1, 3, 4])

In [ ]:
#Random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor

tensor([[[0.7088, 0.8281, 0.6787,  ..., 0.2634, 0.4996, 0.0793],
         [0.2653, 0.5066, 0.5664,  ..., 0.1143, 0.6751, 0.2013],
         [0.3090, 0.5020, 0.8527,  ..., 0.0104, 0.8441, 0.0675],
         ...,
         [0.9383, 0.2201, 0.9963,  ..., 0.7662, 0.8976, 0.4574],
         [0.6127, 0.4742, 0.6410,  ..., 0.3525, 0.4353, 0.7283],
         [0.3318, 0.1446, 0.9815,  ..., 0.1977, 0.9841, 0.1150]],

        [[0.7996, 0.7159, 0.1336,  ..., 0.0582, 0.7341, 0.5011],
         [0.1063, 0.0092, 0.9706,  ..., 0.7859, 0.5800, 0.8330],
         [0.1167, 0.1542, 0.7603,  ..., 0.4989, 0.6991, 0.2324],
         ...,
         [0.5505, 0.5476, 0.7454,  ..., 0.6348, 0.0441, 0.3024],
         [0.0921, 0.8751, 0.4401,  ..., 0.1062, 0.6156, 0.3899],
         [0.3343, 0.4248, 0.7884,  ..., 0.5755, 0.9026, 0.3363]],

        [[0.4261, 0.8061, 0.3702,  ..., 0.8304, 0.1381, 0.3088],
         [0.0858, 0.6542, 0.9306,  ..., 0.7344, 0.9927, 0.5368],
         [0.0658, 0.4688, 0.4570,  ..., 0.8708, 0.8514, 0.

In [ ]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [ ]:
#tenosor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tnsors and tensors-like

In [ ]:
#Use torch.range()
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Crating tensor like
one_to_ten_like = torch.zeros_like(input = one_to_ten)
one_to_ten_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tenosr Datatype

**NOTE:** Tesnosr datatype is one of the three vig errors with PyTorch & Deeplearning:

1. Tensor not right datatype
2. Tenosr not right shape
3. Tenosr not on the right device

In [ ]:
#float 32 tensor
float_32_tesnor = torch.tensor([3.0,6.0,9.0],
                               dtype= None,             # What datatype is the tenosr (float32 float 16 etc)
                               device = None,            # what device is your tenosr on
                               requires_grad = False)     # Whether or not to track gradiens with this tensors operation
float_32_tesnor

tensor([3., 6., 9.])

In [ ]:
# float 16 tesnsor
float_16_tensor = float_32_tesnor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tesnor

tensor([ 9., 36., 81.])

### Getting information from tensors (attributes)

1. Tensor not right datatype -> tensor.dtype
2. Tenosr not right shape -> tensor.shape
3. Tenosr not on the right device -> tensor.device

In [ ]:
#Random Tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6094, 0.5044, 0.3615, 0.8808],
        [0.5098, 0.7280, 0.9316, 0.7458],
        [0.3146, 0.8430, 0.7202, 0.5954]])

In [ ]:
#finding details of tensor

print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.6094, 0.5044, 0.3615, 0.8808],
        [0.5098, 0.7280, 0.9316, 0.7458],
        [0.3146, 0.8430, 0.7202, 0.5954]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


In [ ]:
get_ipython().system('echo "# PyTorch-Tutorial" >> README.md')
get_ipython().system('git init')
get_ipython().system('git add README.md')
get_ipython().system('git commit -m "first commit"')
get_ipython().system('git branch -M main')
get_ipython().system('git remote add origin git@github.com:CaptJack05/PyTorch-Tutorial.git')
get_ipython().system('git push -u origin main')

Reinitialized existing Git repository in /content/.git/
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@22098254e568.(none)')
error: remote origin already exists.
error: src refspec main does not match any
error: failed to push some refs to 'github.com:CaptJack05/PyTorch-Tutorial.git'
