<a href="https://colab.research.google.com/github/CaptJack05/ML/blob/main/__0_pyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pytorch Basics

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


### Types of Tenosr

> Add blockquote



In [3]:
#Scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [4]:
scalar.ndim


0

In [5]:
scalar.shape


torch.Size([])

In [6]:
#vector
vector = torch.tensor([5,7])
vector


tensor([5, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]],])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
#4-D TENSOR

TENSOR4 = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]],
                       [[1, 2, 3],
                        [4, 5, 6],
                  [7, 8, 9]]])
TENSOR4

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
TENSOR4.ndim

3

In [17]:
TENSOR4.shape

torch.Size([2, 3, 3])

### Random Tesors


Why random tesors ?

Random tesnosors are important because the way many neural ntworks learns is that tehy start with tensors full of random numbers and then adjust those random numvers to better represent the data.

'Start with random numbers -> look at data -> update random numbers -> look at data -> update random nmbers '

In [18]:
# Create a random tensor

random_tensor = torch.rand(1,3,10)
random_tensor

tensor([[[0.9879, 0.2095, 0.5152, 0.1280, 0.3880, 0.4105, 0.6507, 0.6142,
          0.1184, 0.1755],
         [0.3646, 0.8025, 0.7303, 0.2222, 0.4239, 0.5099, 0.5437, 0.4023,
          0.6726, 0.6025],
         [0.1050, 0.9001, 0.6322, 0.5026, 0.5674, 0.7297, 0.5019, 0.8802,
          0.0441, 0.2697]]])

In [19]:
random_tensor.ndim

3

In [20]:
random_tensor.shape

torch.Size([1, 3, 10])

In [21]:
#Random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor

tensor([[[0.4603, 0.9758, 0.3399,  ..., 0.1586, 0.7897, 0.3555],
         [0.2628, 0.3908, 0.6429,  ..., 0.1809, 0.6429, 0.3864],
         [0.4644, 0.7650, 0.6758,  ..., 0.0655, 0.7908, 0.7796],
         ...,
         [0.3866, 0.1909, 0.7638,  ..., 0.2231, 0.5911, 0.5443],
         [0.2277, 0.6011, 0.3179,  ..., 0.1398, 0.4605, 0.9394],
         [0.1167, 0.1338, 0.8556,  ..., 0.7246, 0.3243, 0.0024]],

        [[0.1547, 0.0776, 0.7232,  ..., 0.3666, 0.1217, 0.0219],
         [0.3390, 0.1505, 0.6718,  ..., 0.3871, 0.4252, 0.0373],
         [0.7713, 0.8512, 0.0877,  ..., 0.1774, 0.1180, 0.0023],
         ...,
         [0.4893, 0.5228, 0.7200,  ..., 0.7414, 0.7036, 0.7599],
         [0.7688, 0.9753, 0.0702,  ..., 0.3663, 0.2212, 0.6598],
         [0.7799, 0.1541, 0.4224,  ..., 0.4300, 0.3412, 0.4065]],

        [[0.2670, 0.0654, 0.4327,  ..., 0.5092, 0.3633, 0.7497],
         [0.5567, 0.6808, 0.0993,  ..., 0.5032, 0.1794, 0.5520],
         [0.5925, 0.7461, 0.7464,  ..., 0.5822, 0.2049, 0.

In [22]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [23]:
#tenosor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
#tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

### Creating a range of tnsors and tensors-like

In [26]:
#Use torch.range()
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# Crating tensor like
one_to_ten_like = torch.zeros_like(input = one_to_ten)
one_to_ten_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tenosr Datatype

**NOTE:** Tesnosr datatype is one of the three vig errors with PyTorch & Deeplearning:

1. Tensor not right datatype
2. Tenosr not right shape
3. Tenosr not on the right device

In [28]:
#float 32 tensor
float_32_tesnor = torch.tensor([3.0,6.0,9.0],
                               dtype= None,             # What datatype is the tenosr (float32 float 16 etc)
                               device = None,            # what device is your tenosr on
                               requires_grad = False)     # Whether or not to track gradiens with this tensors operation
float_32_tesnor

tensor([3., 6., 9.])

In [29]:
# float 16 tesnsor
float_16_tensor = float_32_tesnor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_16_tensor*float_32_tesnor

tensor([ 9., 36., 81.])

### Getting information from tensors (attributes)

1. Tensor not right datatype -> tensor.dtype
2. Tenosr not right shape -> tensor.shape
3. Tenosr not on the right device -> tensor.device

In [31]:
#Random Tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2410, 0.0954, 0.8304, 0.9958],
        [0.7775, 0.0806, 0.1288, 0.8893],
        [0.4124, 0.9407, 0.6114, 0.9981]])

In [32]:
#finding details of tensor

print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.2410, 0.0954, 0.8304, 0.9958],
        [0.7775, 0.0806, 0.1288, 0.8893],
        [0.4124, 0.9407, 0.6114, 0.9981]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Maniuplating Tensors (tensor operations)
Tensor operation includes:

* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication(Element wise)
* Matrix multiplication

In [33]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [34]:
tensor-10


tensor([-9, -8, -7])

In [35]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [36]:
torch.mul(tensor,10)

tensor([10, 20, 30])

### Matrix Multiplication
two main ways of performing multiplication in neural netowrks and deep learning .

1. Element wise multiplication
2. Matrix multiplication(dot product)


Two main rules that permfomrin matrix multiplication need to satisfy

1. This inner dimensions mut match:
2. The resulting matrix has the shape of the outer dimension

In [39]:
# Element wise multiplication

print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [40]:
# Dot product

print(tensor, ".", tensor)
print(f"Equals: {tensor.matmul(tensor)}")

tensor([1, 2, 3]) . tensor([1, 2, 3])
Equals: 14


In [41]:
%%time
value = 0
for i in tensor:
  value += i*i
print(value)

tensor(14)
CPU times: user 1.13 ms, sys: 1 ms, total: 2.13 ms
Wall time: 2.29 ms


In [42]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 222 µs, sys: 14 µs, total: 236 µs
Wall time: 252 µs


tensor(14)

### One of the most common errors in deep learning : shape errors

In [44]:
#shape for maix multiplication

tensor_A = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor_B = torch.tensor([[7,10],
                       [8,11],
                       [9,12]])



In [45]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [52]:
#torch.mm(tensor_B, tensor_B)
# Shape error

In [53]:
#Transposed
tensor_B.T, tensor_B.T.shape , tensor_A.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]),
 torch.Size([3, 2]))

In [54]:
torch.mm( tensor_B.T, tensor_A)

tensor([[ 76, 100],
        [103, 136]])

### Finding  min max mean sum etx ( tensor aggregation)

In [56]:
#creating the tensor
x = torch.arange(0,100,10)
x

In [57]:
# finding the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [58]:
#finding the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [60]:
#mean  note: torch.mean() function reqires a tensor of float32 datatypes
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [61]:
#sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### finding the positional  min and max

In [62]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [64]:
x.argmin()

tensor(0)

In [65]:
x.argmax()

tensor(9)

### Reshaping , stacking , sqeezing and unsqueezing tensors

* Reshaping - reshapes an input tnesor to a defined shape
* View - Return a view of an input tensor of certain shpae but keep the same memory as original tensor
* Stacking - Combine mutiple tensors on top of each other (vstack) or side by side(hstack)
* Sqeeze- remove all 1 dimension from a tensor
* Unsqeeze - add a 1 dimension to a target tensor
* permute - return a view of the input with dimension permuted(swapped) in a certain way

In [66]:
x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [71]:
#add an extra dimension
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape


(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [72]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
#Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [74]:
#changing z changes x as a view of tensor shares the same memory as the original tensor

z[:,0] = 5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))