<a href="https://colab.research.google.com/github/CaptJack05/ML/blob/main/__0_pyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pytorch Basics

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


### Types of Tenosr

> Add blockquote



In [3]:
#Scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [4]:
scalar.ndim


0

In [5]:
scalar.shape


torch.Size([])

In [6]:
#vector
vector = torch.tensor([5,7])
vector


tensor([5, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]],])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
#4-D TENSOR

TENSOR4 = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]],
                       [[1, 2, 3],
                        [4, 5, 6],
                  [7, 8, 9]]])
TENSOR4

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
TENSOR4.ndim

3

In [17]:
TENSOR4.shape

torch.Size([2, 3, 3])

### Random Tesors


Why random tesors ?

Random tesnosors are important because the way many neural ntworks learns is that tehy start with tensors full of random numbers and then adjust those random numvers to better represent the data.

'Start with random numbers -> look at data -> update random numbers -> look at data -> update random nmbers '

In [18]:
# Create a random tensor

random_tensor = torch.rand(1,3,10)
random_tensor

tensor([[[0.6153, 0.2052, 0.9012, 0.8194, 0.6900, 0.9138, 0.3410, 0.0828,
          0.9887, 0.7245],
         [0.5261, 0.5392, 0.5262, 0.3976, 0.1870, 0.3495, 0.4261, 0.8932,
          0.4241, 0.2377],
         [0.4773, 0.3313, 0.3428, 0.1142, 0.8215, 0.7729, 0.9333, 0.5707,
          0.1578, 0.1311]]])

In [19]:
random_tensor.ndim

3

In [20]:
random_tensor.shape

torch.Size([1, 3, 10])

In [21]:
#Random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor

tensor([[[0.2096, 0.5926, 0.1842,  ..., 0.5259, 0.0284, 0.3225],
         [0.7408, 0.8828, 0.9981,  ..., 0.6072, 0.8886, 0.0769],
         [0.5554, 0.2293, 0.7747,  ..., 0.8863, 0.6770, 0.8007],
         ...,
         [0.8210, 0.0203, 0.0059,  ..., 0.1967, 0.1501, 0.6991],
         [0.7638, 0.9607, 0.5795,  ..., 0.0256, 0.0814, 0.2229],
         [0.3524, 0.1117, 0.7123,  ..., 0.0391, 0.3853, 0.3112]],

        [[0.3104, 0.7862, 0.4253,  ..., 0.9933, 0.9762, 0.2441],
         [0.6019, 0.1058, 0.8513,  ..., 0.3779, 0.7526, 0.8325],
         [0.4365, 0.2737, 0.9250,  ..., 0.5457, 0.6205, 0.6744],
         ...,
         [0.9558, 0.0345, 0.9179,  ..., 0.9731, 0.1238, 0.2193],
         [0.7844, 0.7785, 0.6906,  ..., 0.1682, 0.2817, 0.5955],
         [0.3489, 0.4104, 0.6540,  ..., 0.4503, 0.3964, 0.7080]],

        [[0.3890, 0.0792, 0.2452,  ..., 0.2410, 0.8299, 0.4399],
         [0.3378, 0.5879, 0.9434,  ..., 0.5358, 0.8793, 0.0997],
         [0.4895, 0.3134, 0.8182,  ..., 0.7371, 0.1111, 0.

In [22]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [23]:
#tenosor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
#tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

### Creating a range of tnsors and tensors-like

In [26]:
#Use torch.range()
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# Crating tensor like
one_to_ten_like = torch.zeros_like(input = one_to_ten)
one_to_ten_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tenosr Datatype

**NOTE:** Tesnosr datatype is one of the three vig errors with PyTorch & Deeplearning:

1. Tensor not right datatype
2. Tenosr not right shape
3. Tenosr not on the right device

In [28]:
#float 32 tensor
float_32_tesnor = torch.tensor([3.0,6.0,9.0],
                               dtype= None,             # What datatype is the tenosr (float32 float 16 etc)
                               device = None,            # what device is your tenosr on
                               requires_grad = False)     # Whether or not to track gradiens with this tensors operation
float_32_tesnor

tensor([3., 6., 9.])

In [29]:
# float 16 tesnsor
float_16_tensor = float_32_tesnor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_16_tensor*float_32_tesnor

tensor([ 9., 36., 81.])

### Getting information from tensors (attributes)

1. Tensor not right datatype -> tensor.dtype
2. Tenosr not right shape -> tensor.shape
3. Tenosr not on the right device -> tensor.device

In [31]:
#Random Tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9278, 0.2906, 0.2764, 0.8202],
        [0.1751, 0.9607, 0.3205, 0.7623],
        [0.0476, 0.8211, 0.6880, 0.8199]])

In [32]:
#finding details of tensor

print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.9278, 0.2906, 0.2764, 0.8202],
        [0.1751, 0.9607, 0.3205, 0.7623],
        [0.0476, 0.8211, 0.6880, 0.8199]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Maniuplating Tensors (tensor operations)
Tensor operation includes:

* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication(Element wise)
* Matrix multiplication

In [33]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [34]:
tensor-10


tensor([-9, -8, -7])

In [35]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [36]:
torch.mul(tensor,10)

tensor([10, 20, 30])

### Matrix Multiplication
two main ways of performing multiplication in neural netowrks and deep learning .

1. Element wise multiplication
2. Matrix multiplication(dot product)


Two main rules that permfomrin matrix multiplication need to satisfy

1. This inner dimensions mut match:
2. The resulting matrix has the shape of the outer dimension

In [37]:
# Element wise multiplication

print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [38]:
# Dot product

print(tensor, ".", tensor)
print(f"Equals: {tensor.matmul(tensor)}")

tensor([1, 2, 3]) . tensor([1, 2, 3])
Equals: 14


In [39]:
%%time
value = 0
for i in tensor:
  value += i*i
print(value)

tensor(14)
CPU times: user 1 ms, sys: 0 ns, total: 1 ms
Wall time: 2.97 ms


In [40]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 601 µs, sys: 0 ns, total: 601 µs
Wall time: 685 µs


tensor(14)

### One of the most common errors in deep learning : shape errors

In [41]:
#shape for maix multiplication

tensor_A = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor_B = torch.tensor([[7,10],
                       [8,11],
                       [9,12]])



In [42]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [43]:
#torch.mm(tensor_B, tensor_B)
# Shape error

In [44]:
#Transposed
tensor_B.T, tensor_B.T.shape , tensor_A.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]),
 torch.Size([3, 2]))

In [45]:
torch.mm( tensor_B.T, tensor_A)

tensor([[ 76, 100],
        [103, 136]])

### Finding  min max mean sum etx ( tensor aggregation)

In [46]:
#creating the tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [47]:
# finding the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [48]:
#finding the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [49]:
#mean  note: torch.mean() function reqires a tensor of float32 datatypes
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [50]:
#sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### finding the positional  min and max

In [51]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [52]:
x.argmin()

tensor(0)

In [53]:
x.argmax()

tensor(9)

### Reshaping , stacking , sqeezing and unsqueezing tensors

* Reshaping - reshapes an input tnesor to a defined shape
* View - Return a view of an input tensor of certain shpae but keep the same memory as original tensor
* Stacking - Combine mutiple tensors on top of each other (vstack) or side by side(hstack)
* Sqeeze- remove all 1 dimension from a tensor
* Unsqeeze - add a 1 dimension to a target tensor
* permute - return a view of the input with dimension permuted(swapped) in a certain way

In [54]:
x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [55]:
#add an extra dimension
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape


(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [56]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
#Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [58]:
#changing z changes x as a view of tensor shares the same memory as the original tensor

z[:,0] = 5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [59]:
# stacking tensor on to of each other
x_stacked = torch.stack([x,x,x], dim = 0)
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [60]:
# stacking tensor on to of each other
x_stacked = torch.stack([x,x,x], dim = 1)
x_stacked

tensor([[5, 5, 5],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]])

### Sqeezing and unsquezzing

In [61]:
# Sqeezing

In [62]:
#unqeezing

In [63]:
#torch.permute - reaarange the dimension of a target tensor in a specified order

x_original = torch.rand(size=(224,224,3))  # [height, width, coulour channels]

x_permuted = x_original.permute(2,0,1)  #shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing(Selecting data from tensors)

indexing in pyTorch is similar to indexing in NumPy



In [65]:
#creating a tensor

x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [69]:
# let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [68]:
# middile bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [67]:
x[0][2][1]

tensor(8)

In [70]:
# target last dimension
x[0,2,2]

tensor(9)

In [ ]:
# usele ":" to select "all" of a target dimension
x[:,0 ]

In [71]:
#to get all values of 0 and 1 dimension but index 1 of 2nd dimension

x[:,:,1]

tensor([[2, 5, 8]])

In [72]:
# to get all values of 0 but only the 1 index of 1st and 2nd diemension
x[:, 1, 1]

tensor([5])

In [73]:
# Get index 0 of 0 th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

## PyTorch tensor & NumPy

Numpy is a popular scientific python numerical computing library

and because of this pyTorch has functionality to interacdt with it

* Data in NumPy , want in PyTorch Tensor -> 'torch.from_numpy(ndarry)'
* Pytorch tensor -> NumPy -> torch.Tensor.numpy()




In [74]:
#NumPy array to tensor
array = np.arange(1,8)
tensor = torch.from_numpy(array)  #arning : when converting from numpy -> pytorch, pytorch reflects the default dtype of np array wihch is long
array, tensor

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [75]:
#change the value of array, what will this do to 'tensor'?
array = array +1
array, tensor

(array([2, 3, 4, 5, 6, 7, 8]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [76]:
#tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility (trying to take random out of random)

### in short how a neural networks learns:

start with random numbers -> tensor operations -> update random numbers to try to make them better reperesentation of data -> again -> again -> again


To reduce the randomness in neural network and PyTorch comes the concept of a **random seed** .

Essentially what the random seed does is "flavour" the randomness

In [77]:
torch.rand(3,3)

tensor([[0.9449, 0.3885, 0.5250],
        [0.6854, 0.3600, 0.2641],
        [0.4499, 0.9847, 0.8693]])