# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch

import torch
# Create random tensor
tensor = torch.rand(7,7)


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
tenosor2 = torch.rand(1,7)
# Perform matrix multiplication
torch.matmul(tensor, tenosor2.T)


tensor([[1.8030],
        [1.7531],
        [1.9297],
        [2.5757],
        [2.0958],
        [1.7683],
        [2.7102]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(seed=RANDOM_SEED)
tensor_A = torch.rand(7,7)
torch
tensor_B = torch.rand(1,7)


# Matrix multiply tensors
torch.matmul(tensor_A, tensor_B.T)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU
torch.cuda.manual_seed(seed = RANDOM_SEED)
tensor_A_onGPU = torch.rand(7,7).cuda()
tensor_A_onGPU

tensor([[0.4910, 0.1235, 0.1143, 0.4725, 0.5751, 0.2952, 0.7967],
        [0.1957, 0.9537, 0.8426, 0.0784, 0.3756, 0.5226, 0.5730],
        [0.6186, 0.6962, 0.5300, 0.2560, 0.7366, 0.0204, 0.2036],
        [0.3748, 0.2564, 0.3251, 0.0902, 0.3936, 0.6069, 0.1743],
        [0.4743, 0.8579, 0.4486, 0.5139, 0.4569, 0.6012, 0.8179],
        [0.9736, 0.8175, 0.9747, 0.4638, 0.0508, 0.2630, 0.8405],
        [0.4968, 0.2515, 0.1168, 0.0321, 0.0780, 0.3986, 0.7742]],
       device='cuda:0')


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [8]:
# Set random seed
RANDOM_SEED = 1234

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
torch.manual_seed(seed = RANDOM_SEED)
tensor_A_onGPU = torch.rand(2,3).to(device)
tensor_B_onGPU = torch.rand(2,3).to(device)



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [13]:
# Perform matmul on tensor_A and tensor_B
out = torch.matmul(tensor_A_onGPU,tensor_B_onGPU.T)
out

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [14]:
# Find max
print(out.max())

# Find min
print(out.min())

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [15]:
# Find arg max
print(out.argmax())


# Find arg min
print(out.argmin())


tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [17]:
from IPython.lib.security import random
# Set seed

RANDOM_SEED = 7

# Create random tensor
torch.manual_seed(seed = RANDOM_SEED)
random_tensor = torch.rand(1,1,1,10)


# Remove single dimensions
random_tensor_squeezed = random_tensor.squeeze()


# Print out tensors and their shapes
random_tensor, random_tensor.shape, random_tensor_squeezed, random_tensor_squeezed.shape


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))